# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
app_identifier "cx.viz.viz-wallet"
username "vovababin@gmail.com"
skip_metadata true
submit_for_review false