# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    # ensure_git_status_clean
    build_number = number_of_commits(all: true)
    increment_build_number(build_number: build_number)
    build_app(scheme: "viz-wallet (iOS)")
    upload_to_app_store(
      force: true,
      skip_screenshots: true,
      skip_metadata: true
    )
  end

  lane :beta do
    # ensure_git_status_clean
    build_number = number_of_commits(all: true)
    increment_build_number(build_number: build_number)
    build_app(
      scheme: "viz-wallet (iOS)",
      include_bitcode: true
    )
    upload_to_testflight(
      skip_submission: true,
      skip_waiting_for_build_processing: true
    )
  end

  desc "Capture and upload screenshots to the App Store"
  lane :screenshots do
    capture_screenshots
    # frame_screenshots(white: true)
    upload_to_app_store(
      overwrite_screenshots: true,
      skip_metadata: true,
      skip_binary_upload: true,
      skip_app_version_update: true
    )
  end
end
